# 使用するテーマ
remote_theme: pages-themes/cayman@v0.2.0

# Markdownの設定
markdown: kramdown

# サイトの基本情報
title: ISUCON14 try by Challenge Club Website
description: A Challenge Club GitHub Pages site.
baseurl: "" 
url: "https://HideakiTakechi.github.io"

# ページ生成に関する設定
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
